const images={
   
   achivements:{
   image1:require('./images/Achievements/image-1.jpg').default,
   image2:require('./images/Achievements/image-2.jpg').default,
   image3:require('./images/Achievements/image-3.jpg').default,
   image4:require('./images/Achievements/image-4.jpg').default,
   image5:require('./images/Achievements/image-5.jpg').default,
   image6:require('./images/Achievements/image-6.jpg').default,
   image7:require('./images/Achievements/image-7.jpg').default,
   image8:require('./images/Achievements/image-8.jpg').default,
   image9:require('./images/Achievements/image-9.jpg').default,
   },
   carousel:{
       image1:require('./images/Carousel/carousel-img-1.jpg').default,
    //    image2:require('./images/Carousel/carousel-img-2.jpg').default,
       image3:require('./images/Carousel/carousel-img-3.jpg').default,
       image4:require('./images/Carousel/carousel-img-4.webp').default,
},
gallery:{
    image1:require('./images/Gallery/IMG-1.jpg').default,
    image2:require('./images/Gallery/IMG-2.jpg').default,
    image3:require('./images/Gallery/IMG-3.jpg').default,
    // image4:require('./images/Gallery/IMG-4.jpg').default,
    // image5:require('./images/Gallery/IMG-5.jpg').default,
    // image6:require('./images/Gallery/IMG-6.jpg').default,
    // image7:require('./images/Gallery/IMG-7.jpg').default,
    // image8:require('./images/Gallery/IMG-8.jpg').default,
    // image9:require('./images/Gallery/IMG-9.jpg').default,
    // image10:require('./images/Gallery/IMG-10.jpg').default,
    image11:require('./images/Gallery/IMG-11.jpg').default,
    image12:require('./images/Gallery/IMG-12.jpg').default,
    image13:require('./images/Gallery/IMG-13.jpg').default,
    image14:require('./images/Gallery/IMG-14.jpg').default,
    image15:require('./images/Gallery/IMG-15.jpg').default,
    image16:require('./images/Gallery/IMG-16.jpg').default,
    image17:require('./images/Gallery/IMG-17.jpg').default,
    image18:require('./images/Gallery/IMG-18.jpg').default,
    image19:require('./images/Gallery/IMG-19.jpg').default,
    image20:require('./images/Gallery/IMG-20.jpg').default,
    image21:require('./images/Gallery/IMG-21.jpg').default,
    image22:require('./images/Gallery/IMG-22.jpeg').default,
    image23:require('./images/Gallery/IMG-23.jpg').default,
    image24:require('./images/Gallery/IMG-24.jpg').default,
},

groceries:{
    image1:require('./images/groceries/IMG-1.jpg').default,
    image2:require('./images/groceries/IMG-2.jpg').default,
    image3:require('./images/groceries/IMG-3.jpg').default,
    image4:require('./images/groceries/IMG-4.jpg').default,
    image5:require('./images/groceries/IMG-5.jpg').default,
},

child:{
    image1:require('./images/child/IMG-1.jpg').default,
    image2:require('./images/child/IMG-2.jpg').default,
    image3:require('./images/child/IMG-3.jpg').default,
    image4:require('./images/child/IMG-4.jpg').default,
    image5:require('./images/child/IMG-5.jpg').default,
},

woman:{
    image1:require('./images/woman/IMG-1.jpg').default,
    image2:require('./images/woman/IMG-2.jpg').default,
    image3:require('./images/woman/IMG-3.jpg').default,
    image4:require('./images/woman/IMG-4.jpg').default,
    image5:require('./images/woman/IMG-5.jpg').default,
},
icons:{
    image1:require("./images/Icons/g-pay.png").default,
    image2:require("./images/Icons/paytm.webp").default,
    image3:require("./images/Icons/phone-pe.png").default,
},
team:{
    image1:require("./images/Team/IMG1.jpg").default,
    image2:require("./images/Team/IMG2.jpg").default,
    image3:require("./images/Team/IMG3.jpg").default,
    image4:require("./images/Team/IMG4.jpg").default,
    image5:require("./images/Team/IMG5.jpg").default,
    image6:require("./images/Team/IMG6.jpg").default,
    image7:require("./images/Team/IMG7.jpg").default,
},
testimonial:{
    image1:require("./images/Testimonials/testimonial-img-1.jpg").default,
    image2:require("./images/Testimonials/testimonial-img-2.jpg").default,
    image3:require("./images/Testimonials/testimonial-img-3.jpg").default,
    image4:require("./images/Testimonials/testimonial-img-4.jpg").default,
    image5:require("./images/Testimonials/testimonial-img-5.jpg").default,
    image6:require("./images/Testimonials/testimonial-img-6.jpg").default,
},
support:{
    image1:require('./images/Support/IMG1.jpg').default,
    image2:require('./images/Support/IMG2.jpg').default,
    image3:require('./images/Support/IMG3.png').default,
    image4:require('./images/Support/IMG4.jpg').default,
    image5:require('./images/Support/IMG5.png').default,
    image6:require('./images/Support/IMG6.jpg').default,
    // image7:require('./images/Support/IMG7.jpg').default,
    image8:require('./images/Support/IMG8.jpeg').default,
    image9:require('./images/Support/IMG9.jpg').default,
    image10:require('./images/Support/IMG10.jpg').default,
    image11:require('./images/Support/IMG11.jpg').default,
    image12:require('./images/Support/IMG12.jpg').default,
    image13:require('./images/Support/IMG13.jpg').default,
    image14:require('./images/Support/IMG14.jpg').default,
    image15:require('./images/Support/IMG15.jpg').default,
},
extra:{
    bgImage:require("./images/inner-pages.png").default,
    qrDownload:require("./images/qr-code.jpeg").default,
    qrCode:require("./images/qr-code-sss.jpg").default,
    servicesImage:require("./images/services.png").default,
}
}

export default images;